#!/bin/bash

# A helyi repót aláírja, a repóban indítva
# A disztribution megállapítása
# A /UHUBUILD/packages-UBK? esetén UBK1, UBK2, UBK3 lesz a $diszt
diszt=$(pwd | sed s/.*packages-// | sed s/\\/.*//)
# Ha nem ott vagyunk, akkor talán a helyi tükör main/$arch mappájában.. 
if [ ! "$diszt" ];then
diszt=$(pwd | sed s/\\/main.*// | sed s/.*pkg\\///)
fi
# Ha ott sem és van Release, akkor az tartalmazza.
if [ -f Release ];then
diszt=$(cat Release | grep Version | sed 's/Version: //')
fi
# Ha ott sem, akkor kilépünk.
if [ ! "$diszt" ];then
echo nem állapítható meg a disztribution!
exit 1
fi
arch=$(pwd | sed s/.*\\///)
if [ $arch = amd64 ] || [ $arch = i386 ];then
rm -f Release*
rm -f Packages*
echo "uhu-reposign $diszt $arch"
uhu-reposign $diszt $arch
else
echo "Csak i386 és amd64 mappában futtatható a szkript!"
fi


