#!/bin/bash
# extrarelease fájl összegyűjtő szkript csomagok újrafordításához
# az apt cache alapján gyűjti össze a $ereldir alá a csomagok extrarelease fájljait

ereldir=extrarelease
rm -rf $ereldir
mkdir $ereldir
for i in $@; do
filename=$(apt-cache show "$i" | grep Filename: |head -1 | sed s/Filename:" "*// | sed s/_i.*// | sed s%.*/%%g)
erelfile=$(echo "$filename" | sed  s%\.[0-9]*$%%g)
extrarelease=$(echo "$filename" | sed s%$erelfile\.%%)
echo "$extrarelease" > $ereldir/$erelfile
done
