#!/bin/bash

# Az ub git tükrében lévő build-depends, depends, sections, priority fájlok
# analízise alapján helyi gyorsan analizálható mappák és benne fájlok létrehozása
# a bdep és rdep szkriptek számára.

gittem=/usr/src/UHUBUILD/UB-UBK1/ub-ubk1
analdir=/usr/src/UHUBUILD/UB-UBK1/devanal
bdep=/usr/src/UHUBUILD/UB-UBK1/devanal/bdep
rdep=/usr/src/UHUBUILD/UB-UBK1/devanal/rdep
section=/usr/src/UHUBUILD/UB-UBK1/devanal/section
priority=/usr/src/UHUBUILD/UB-UBK1/devanal/priority

rm -rf $analdir
mkdir -p $bdep $rdep $section $priority

cd $gittem
git pull
cd -
for j in `ls -1 $gittem`;do
  echo $j
  touch $bdep/$j
  touch $rdep/$j
  touch $section/$j
  touch $priority/$j
  if [ -f $gittem/$j/build-depends ];then
    cat $gittem/$j/build-depends | sed s/-dev$//g >>$bdep/$j
  fi

  if [ -f $gittem/$j/packages/${j}/depends ];then
    cat $gittem/$j/packages/${j}/depends | sed s/-dev$//g >>$rdep/$j
  else
    for k in `ls $gittem/$j/packages`;do
      if [ -f $gittem/$j/packages/${j}/${k}/depends ];then
	cat $gittem/$j/packages/${j}/${k}/depends >>$depends/$j
	break
      fi
    done
  fi

  if [ -f $gittem/$j/packages/${j}/section ];then
    cat $gittem/$j/packages/${j}/section >>$section/$j
  else
    for k in `ls $gittem/$j/packages`;do
      if [ -f $gittem/$j/packages/${k}/section ];then
	cat $gittem/$j/packages//${k}/section >>$section/$j
	break
      fi
    done
  fi
  if [ -f $gittem/$j/packages/${j}/priority ];then
    cat $gittem/$j/packages/${j}/priority >>$priority/$j
  else
    for k in `ls $gittem/$j/packages`;do
      if [ -f $gittem/$j/packages/${k}/priority ];then
	cat $gittem/$j/packages//${k}/priority >>$priority/$j
	break
      fi
    done
  fi
done
