#!/bin/bash

# A paraméterkéntként megadott csomagból építkező csomagtalálatok
# amiknek a build-depends fájljában a paraméter szerepel
#!! a bdeprak szkript lefuttatása után használható csak !!

bdep=/usr/src/UHUBUILD/UB-UBK1/devanal/bdep
rdep=/usr/src/UHUBUILD/UB-UBK1/devanal/rdep
gittem=/usr/src/UHUBUILD/UB-UBK1/ub-ubk1

grep ^$1$ $bdep/* | sed s/:.*//g | sed s%.*\/%%g
