#!/bin/bash

# Eltávolítja a build-depends fájlban felesegesen szereplő elemeket
# El kell távolítani, ha valamely másik elem a függőségeként magával hozza
# A tagot az eredeti listahalmaz minden egyes elemének függőségei közt kell keresni
# Ha nem szerepel, akkor ő maga belemegy, Ha szerepel, akkor az, akinél szerepel

eredetilista=$(cat build-depends | sort -u)

for listaelem in $eredetilista; do # mindegyik listaelemet végignézem
    for alelem in $eredetilista; do # minden alelem
    alelemdeps=$(apt-cache depends "$alelem" | grep Függ | sed s/"  Függ ettől: "//g | sort -u)
    alelemdep=$(echo "$alelemdeps" | grep -E ^"$listaelem"$)
      if [ "$alelemdep" == "$listaelem" ]; then # ha a szűrő nemüres
	  echo "$listaelem"" csomagot felhúzza: ""$alelem"
	  continue 2
      fi
     done
     echo $listaelem
     ujlista=$(echo -e "$listaelem"'\n'"$ujlista")
done
echo "$ujlista" | sort -u > build-depends-uj
