#!/bin/bash -e

# Extrarelease fájlok összegyűjtő szkriptje csomaghalmaz újrafordításához.

# Az első paraméterben megadott architektúrának megfelelő ftp lelőhelyről összegyűjti a 
# megadott csomagnevek aktuális extrarelease értékeit egy újonnan a munkakönyvtárban létrehozott mappába.
# Az ide létrehozott fájlokat a /usr/src/UHUBUILD/ megfelelő mappájába másolva a build
# rendszer már azokkal fog dolgozni és a létrejövő csomag extrarelease értéke nagyobb lesz az ftp-n találhatónál.

function hiba () {
    echo $1
	echo 'Használat: curlextrarel <i386|amd64> <csomagsorozat> '
	exit 1
}


diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|UBK1$\|2$\|3$' | sed s/.*-//)

if [ ! $diszt ];then
    hiba "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
fi

if [ ! "$(echo $1 | grep '^i386$\|^amd64$')" ]; then
    hiba "Nem jó a $1 architektúra paraméter"
fi

if [ ! "$2" ];then
    hiba "Nincs megadva egy csomag sem!"
fi

arch=$1
erelmappa=erel-${arch}

# csak a csomaghalmaz kell a paraméterlistából
csomaghalmaz=""
for csomag in "$@" ; do
    if [ ! $csomag == $1 ]; then
        csomaghalmaz=$(echo -e "$csomaghalmaz"'\n'"$csomag")
    fi
done

curlcim=ftp://ftp.ubk.hu/pkg/${diszt}/main/${arch}/

# takarítások
rm -f tmpfile
rm -rf $erelmappa
mkdir $erelmappa

echo " Az aktuális extrarelease fájlok az $erelmappa mappába kerülnek."

timeout 10 lynx -connect_timeout=5 -read_timeout=5 -passive-ftp -listonly -dump $curlcim  | sed -r 's/^.*\/([^\/]+)\/?$/\1/' | grep -E "uhu"$ > tmpfile

for i in $csomaghalmaz;do
    filenev=$(grep ^"${i}"_ tmpfile)
    echo $filenev
    nev=$(echo $filenev | sed "s/_$arch.*//g")
    extrareleasenev=$(echo $nev | sed  s/\.[0-9]*$//)
    extrarelease=$(echo $nev| sed s/.*-//g | sed s/[0-9]*\\.//g)
    #echo "$filenev $extrareleasenev $extrarelease"
    echo -e $extrarelease'\n' > $erelmappa/$extrareleasenev
done
# takarítás
rm -f tmpfile
