#!/bin/bash -e

# Extrarelease fájlok összegyűjtő szkriptje csomagok újrafordításához.

# Az első paraméterben megadott disztribúciónak megfelelő ftp lelőhelyről összegyűjti a 
# megadott csomagnevek aktuális extrarelease értékeit egy újonnan a munkakönyvtárban létrehozott extrarelease mappába.
# Az ide létrehozott fájlokat a /usr/src/UHUBUILD/misc-UBK1/extrarelease/ mappába másolva a build
# rendszer már azokkal fog dolgozni és a létrejövő csomag extrarelease értéke nagyobb lesz az ftp-n találhatónál.

if [ ! "$(echo $1 | grep '^1$\|^2$\|^3$')" ]; then
    echo "Nem jó a $1 disztribúció paraméter"
    echo 'Használat: curlextrarel <1|2|3> <csomagsorozat> ' >&2
	exit 1
fi
if [ ! "$2" ];then
    echo "Nincs megadva egy csomag sem!"
    echo 'Használat: curlextrarel <1|2|3> <csomagsorozat> ' >&2
	exit 1
fi
echo " Az aktuális extrarelease fájlok az exrarelease mappába kerülnek."
        curlcim=ftp://ftp.ubk.hu/pkg/UBK$1/main/i386/
rm -rf extrarelease cimek
mkdir extrarelease cimek
rm -f csomaglista

# disztrib paraméter kiszedése a paraméterlistából
frisscsomagok=""
for num in "$@" ; do
  if [ ! $num == $1 ]; then
  frisscsomagok=$(echo -e "$frisscsomagok"'\n'"$num")
  fi
done
timeout 10 lynx -connect_timeout=5 -read_timeout=5 -passive-ftp -listonly -dump $curlcim  | sed -r 's/^.*\/([^\/]+)\/?$/\1/' | grep -E "uhu"$ > csomaglista

for i in $frisscsomagok;do
	  filenev=$(grep ^"$i"_ csomaglista)
nev=$(echo $filenev | sed s/_i386.*//g)
extrareleasenev=$(echo $nev | sed  s/\.[0-9]*$//)
extrarelease=$(echo $nev| sed s/.*-//g | sed s/[0-9]*\\.//g)
#echo "$filenev $extrareleasenev $extrarelease"
echo -e $extrarelease'\n' > extrarelease/$extrareleasenev
done
rm -f csomaglista
