#!/bin/bash -e

# extrarelease fájl összegyűjtő szkript csomagok újrafordításához

function ftplista() {
timeout 10 lynx -connect_timeout=5 -read_timeout=5 -passive-ftp -listonly -dump $1  | sed -r 's/^.*\/([^\/]+)\/?$/\1/' | grep -E "uhu"$
}

function hiba () {
    echo $string
	echo 'Használat: extrarel <i386|amd64>'
	exit 1
}


diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|UBK1$\|2$\|3$' | sed s/.*-//)
if [ ! $diszt ];then
    string="Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
    hiba
fi

if [ ! "$(echo $1 | grep '^i386$\|^amd64$')" ]; then
    string="Nem jó a $1 architektúra paraméter"
    hiba
fi
arch=$1
urlcim=ftp://ftp.ubk.hu/pkg/$diszt/main/$arch
echo " az aktuális extrarelease fájlok az exrarelease-$arch mappába kerülnek"

rm -f csomagok

ftplista $urlcim > csomagok
rm -rf extrarelease-$arch
mkdir extrarelease-$arch

for filenev in `cat csomagok`;do
nev=$(echo $filenev | sed "s/_$arch.*//g")
extrareleasenev=$(echo $nev | sed  s/\.[0-9]*$//)
extrarelease=$(echo $nev| sed s/.*-//g | sed s/[0-9]*\\.//g)
#echo "$filenev $extrareleasenev $extrarelease"
echo -e $extrarelease'\n' > extrarelease-$arch/$extrareleasenev
done
rm -rf csomagok
