#!/bin/bash -e

# A paraméter ubét lefordítja 64 bitre

if [ $# = 0 ]; then
	echo 'Paraméterként fordítandó cucc kell' >&2
	exit 1
fi

diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|UBK1$\|2$\|3$' | sed s/.*-//)
if [ ! $diszt ];then
echo "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
exit 1
fi

kisdiszt=$(echo $diszt | tr [:upper:] [:lower:])

echo "build-$kisdiszt"
build-$kisdiszt -ns -64 $1
