#!/bin/bash
# Összegyűjti a paraméterként megadott listafájlból a frissíthető csomagokat.

function hiba () {
    echo $string
	echo 'Használat: frissgyujt <listafájl>'
	exit 1
}

diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|UBK1$\|2$\|3$' | sed s/.*-//)

if [ ! "$1" ]; then
    string="listafájl paraméter kell!"
    hiba
fi

if [ ! $diszt ];then
    string="Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
    hiba
fi

kisdiszt=$(echo $diszt | tr [:upper:] [:lower:])
workdir=`pwd`
gitdir=~/gittek/ubk/ub-$kisdiszt

if [ ! -d $gitdir ];then
    string="Nincs klónozott $gitdir !"
    hiba
fi


listafile=$1
if [ ! -f $listafile ];then
    string="Nincs $listafile listafájl!"
    hiba
fi

echo "A $gitdir frissítése"
cd $gitdir >/dev/null
git pull
cd - >/dev/null

frissmappa=friss-$listafile
rm -rf $frissmappa
mkdir -p $frissmappa
rm -f $listafile-uj $listafile-ujnevek

for i in `cat $workdir/$listafile`;do
    if [ -d $gitdir/$i ]; then
        echo $i
        cd $gitdir/$i
        over=$(cat version)
        ujver=$(uhubuild-u2d)
        if [ ! "$over" == "$ujver" ];then
            cp -a $gitdir/$i $workdir/$frissmappa
            echo "$i $over -> $ujver" >>$workdir/$listafile-uj
#            echo $i >>$workdir/$listafile-ujnevek
        fi
        cd - > /dev/null
    fi
done
echo
if [ -f $listafile-uj ];then
echo "A frissíthető csomagok a $listafile-uj fájlban vannak felsorolva."
echo "A frissíthető ubék a $workdir/$frissmappa mappában vannak"
else
echo "Nincs frissíthető csomag."
fi
