#!/bin/bash
#leteszteli terminálban a listafájlban felsorolt csomagok frissíthetőségét

function hiba () {
    echo $string
	echo 'Használat: listateszt <listafájl>'
	exit 1
}

diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|UBK1$\|2$\|3$' | sed s/.*-//)
if [ ! $diszt ];then
    string="Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
fi

if [ ! "$1" ]; then
	string="listafájl paranéter kell!"
	hiba
fi

listafile=$1

if [ ! -f $listafile ];then
        string="nincs $listafile listafájl!"
        hiba
fi

kisdiszt=$(echo $diszt | tr [:upper:] [:lower:])
workdir=`pwd`
gitdir=~/gittek/ubk/ub-$kisdiszt

if [ ! -d $gitdir ];then
    string="Nincs klónozott $gitdir !"
    hiba
fi

echo "A $gitdir frissítése"
cd $gitdir >/dev/null
git pull
cd - >/dev/null

for i in `cat $listafile`;do
    if [ -d $gitdir/$i ]; then
        cd $gitdir/$i >/dev/null
            u2dinfo
        cd - >/dev/null
    else
        echo "Nincs $gitdir/$i mappa!"
    fi
done
