#!/bin/bash

# Az orig és mod mappák tartalmáról a paraméterév.patch foltot hoz létre

function hiba () {
    echo $1
	echo 'Használat: paccs <foltnév>'
	echo "A munkamappában kell lennie vagy orig és mod, vagy * és *.patched mappa párnak"
	exit 1
}

if [ -z "$1" ]; then
    hiba "foltnév paraméter kell"
fi

if [ -d orig ] && [ -d mod ];then
    diff -Nur orig mod > "$1".patch
    exit 0
else
    mod=$(ls -1 | grep patched)
    if [ ! "$mod" ]; then
        hiba "Nincs összehasonlítható mappapáros"
    fi
    orig=$(echo $mod | sed s/\.patched//)
    if [ ! -d $orig ]; then
        hiba "Nincs összehasonlítható mappapáros"
    else
        diff -Nur $orig $mod > "$1".patch
    fi
fi
