#!/bin/bash

# A paraméterkéntként megadott csomagot futási időben használó csomagok
# vagyis amiknek a depends fájljában a paraméter szerepel
#!! a bdeprak szkript lefuttatása után használható csak !!

bdep=/usr/src/UHUBUILD/UB-UBK1/devanal/bdep
rdep=/usr/src/UHUBUILD/UB-UBK1/devanal/rdep
gittem=/usr/src/UHUBUILD/UB-UBK1/ub-ubk1

if [ -d $rdep ];then
grep ^$1$ $rdep/*  | sed s/:.*//g | sed s%.*\/%%g
else
echo "Nincs $rdep mappa, ezt a bdep szkript hozza létre!"
fi
