#!/bin/bash

ubtukor=/usr/src/UHUBUILD/gitt
ubdir=$ubtukor/ub
uboff=$ubtukor/ub-3-official
celdir=/usr/src/UHUBUILD/UB-3/forrasok
ereldir=/usr/src/UHUBUILD/UB-3/extrareleasemappa

rm -rf $ereldir $celdir
mkdir -p $ereldir $celdir

if [ ! -d $ubtukor ]; then
echo "A $ubtukor könyvtár létrehozása"
mkdir -p $ubtukor
fi

if [ ! -d $ubdir ]; then
echo "A $ubdir klónozása"
cd $ubtukor
git clone https://github.com/uhulinux/ub
cd - > /dev/null
fi

if [ ! -d $uboff ]; then
echo "A $uboff klónozása"
cd $ubtukor
git clone https://github.com/uhulinux/ub-3-official
cd - > /dev/null
fi

# tükör frissítés
echo "Az ub helyi tükrök frissítése"
cd $ubdir
git pull
cd -> /dev/null
cd $uboff
git pull
cd - > /dev/null

revdep-rebuild 1 "$@"
echo A lefordítandó csomagok; echo
for i in `cat ubrend`; do
echo  $i
if [ -d $ubdir/$i ]; then
cp -r $ubdir/$i $celdir/
else
if [ -d $uboff/$i ]; then
cp -r $uboff/$i $celdir/
else
echo "nincs ""$i"" könyvtár"
fi
fi

if [ ! -d $celdir/$i/sources ]; then
mkdir $celdir/$i/sources
fi
done

for i in `cat csomagrend`; do
filename=$(apt-cache show "$i" | grep Filename: |head -1 | sed s/Filename:" "*// | sed s/_i.*// | sed s%.*/%%g)
erelfile=$(echo "$filename" | sed  s%\.[0-9]*$%%g)
extrarelease=$(echo "$filename" | sed s%$erelfile\.%%)
echo "$extrarelease" > $ereldir/$erelfile
done

echo ; echo "A lefordítandó csomagok legfrissebb ubéi a $celdir mappában vannak."
echo "A csomagok extrarelease fájljai a $ereldir mappában vannak."
echo "A fordítási sorrend a ./ubsorrend fájl szerint ajánlott."
