#!/bin/bash

# UHU-3/2.2/RIA -hoz felfrissíti az ub helyi tükreit.
# A megadott frissítendő paraméterlista alapján
# legyártja az ubsorrend fájlt és előhalássza az éppen elérhető
# legfrissebb ubéke a $celdir mappába, ezekbe sources mappát is készít.
# A csomagokhoz szükséges aktuális extrarelease fájlokat elkészíti
# a $ereldir mappába

diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-\|UBK1$\|2.2$\|3$\|dev$' | sed s/.*-//)
if [ ! $diszt ];then
echo "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
exit 1
fi
workdir=`pwd`
ubtukor=/usr/src/UHUBUILD/ubgit

celdir=$workdir/forrasok
ereldir=$workdir/extrareleasemappa
ubdir=$ubtukor/ub-$diszt

rm -rf $ereldir $celdir
mkdir -p $ereldir $celdir

if [ ! -d $ubtukor ]; then
mkdir -p $ubtukor
fi
if [ ! -d $ubdir ]; then
echo "A $ubdir klónozása"
cd $ubtukor
git clone https://github.com/uhulinux/ub-$diszt
cd - > /dev/null
else
echo "A $ubdir frissítése"
cd $ubdir
git pull
cd - > /dev/null
fi

revdep-rebuild 1 "$@"
echo A lefordítandó csomagok; echo
for i in `cat ubrend`; do
echo  $i
if [ -d $ubdir/$i ]; then
cp -r $ubdir/$i $celdir/
else
echo "nincs ""$i"" könyvtár"
fi

if [ ! -d $celdir/$i/sources ]; then
mkdir $celdir/$i/sources
fi
done

for i in `cat csomagrend`; do
filename=$(apt-cache show "$i" | grep Filename: |head -1 | sed s/Filename:" "*// | sed s/_i.*// | sed s%.*/%%g)
erelfile=$(echo "$filename" | sed  s%\.[0-9]*$%%g)
extrarelease=$(echo "$filename" | sed s%$erelfile\.%%)
echo "$extrarelease" > $ereldir/$erelfile
done

echo ; echo "A lefordítandó csomagok legfrissebb ubéi a $celdir mappában vannak."
echo "A csomagok extrarelease fájljai a $ereldir mappában vannak."
echo "A fordítási sorrend a ./ubrend fájl szerint ajánlott."
