#!/bin/bash -e

# Az ubrend fájl sorrendje alapján elvégzi a fordítást a forrasok mappába elhelyezett
# ubék használatával. Ha talál az ubrend fájlban felsorolt mappát, akkor azt a fordítási mappába helyezi,
# majd elvégzi a fordítást. Ha sikeres, akkor áthelyezi ezt a mappát a keszek mappába, és próbálkozik az
# ubrend fájlban lévő következő elemmel.
# Ha nem sikerül a fordítás és nem kapott a szkript parancssori paramétert, akkor áthelyezi ezt a mappát a failed
# mappába és veszi a következő ubrend elemét.
# Ha nem sikerül a fordítás és volt parancssori paraméter, akkor leáll a szkript.

diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-\|UBK1$\|2.2$\|3$\|dev$' | sed s/.*-//)
if [ ! $diszt ];then
echo "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
exit 1
fi

workdir=`pwd`
celdir=$workdir/keszek
forrdir=$workdir/forrasok
faileddir=$workdir/failed
sorrendfile=$workdir/ubrend
pkgdir=/usr/src/UHUBUILD/packages-$diszt
debug=$1

if [ ! -f $sorrendfile ];then
echo "Nincs $sorrendfile fordítási sorrend fájl!"
exit 1
fi
# Mappagyártás, ha nincs
if [ -d $forrdir ];then
mkdir -p $forrdir
fi
if [ -d $celdir ];then
mkdir -p $celdir
fi
if [ -d $faileddir ];then
mkdir -p $faileddir
fi

for i in `cat $sorrendfile`; do
if [ -d $forrdir/$i ]; then
mv $forrdir/$i ./
# sources mappa kell
mkdir -p $i/sources
# Hash-sum hiba megelőzése
cd $pkgdir >/dev/null
rm -f Packages*
uhu-scanpkgs
cd - /dev/null
if [ ! "$debug" ];then
set +e
build-$diszt -ns $i
if [ $? -eq 2 ]; then
mv $i $faileddir/
else
mv $i $celdir/
fi
set -e
else
build-3 -ns $i
mv $i $celdir/
fi
fi
done
echo "A $forrdir mappa üres"
