#!/bin/bash

# Az elkészült csomagok ubéit elhelyezi a helyi github tükörbe, utána kiíratja a github státuszt.
# A státusz ellenőrzése után mehet a commit és a push.
# használható az ubk1, ubk2 és ubk3 github helyi tükreinél is.

workdir=`pwd`
diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|1$\|2$\|3$' | sed s/.*-//)
if [ ! $diszt ];then
echo "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
exit 1
fi

kisdiszt=$(echo $diszt | tr [:upper:] [:lower:])

keszdir=$workdir/keszek
if [ ! -d $keszdir ];then
echo "Nincs $keszdir !"
exit 1
fi

ubdir=~/gittek/ubk/$kisdiszt
if [ ! -d $ubdir ];then
echo "Nincs klónozott $ubdir !"
exit 1
fi

cd $ubdir
git pull

for i in `ls -1 $keszdir`;do
rm -rf $i
cp -r $keszdir/$i ./
rm -rf $i/sources
git add $i
done

git status
cd -
