#!/bin/bash

# A fordítási sorrendfájlok összefűzése

diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|UBK1$\|2$\|3$' | sed s/.*-//)
if [ ! $diszt ];then
echo "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
exit 1
fi

kisdiszt=$(echo $diszt | tr [:upper:] [:lower:])
gitmappa=~/gittek/ubk/ub-${kisdiszt}

echo gittmapa aktualizálása
cd $gitmappa
git pull
cd -

for i in `ls -1 $gitmappa/Build-order/*txt`;do
if [ ! "$(echo $i | grep chroot)" ];then
cat $i >>osszubrend
fi
done
