#!/bin/bash

# u2d alapján módosítja a $workdirben lévő ubék version fájját, ha az elérhető verzió más.
# Ha más, mint az eredi, akkor a release fájl értékét 1 -re állítja
# sources mappát készít, ha az nem lenne

function hiba () {
    echo $string
    echo "Használat: verno <mappa>"
	exit 1
}

workdir=$1
if [ ! "$workdir" ];then
    string="mappa paraméter kell!"
    hiba
fi

if [ ! -d $workdir ];then
    string="Nincs $workdir mappa!"
    hiba
fi

for i in `ls -1 $workdir`;do
        echo "forrás: $i"
        cd $workdir/$i
        # ha nem lenne
        mkdir -p sources
        over=$(cat version)
        ujver=$(uhubuild-u2d)
        if [ ! "$ujver" ];then
        ujver=$(uhubuild-u2d)
        fi
        if [ ! "$ujver" ];then
        echo "A $i ub u2d fájlja hibás!"
        break
        fi
        if [ ! "$over" == "$ujver" ];then
            echo "$i $over -> $ujver"
            echo $ujver >version
            echo 1 >release
        fi
        cd - > /dev/null
done
