#!/bin/bash

# A helyi csomagkészletben az egyes csomagok függőségeinek létét vizsgálja a dpkg-deb segítségével.
# A észlelt hiányosságok a csujra és a fugghibak fájlokban lesznek felsorolva


# csak a fordítási mappában megy és színes és ub tároló frissül
. ubfriss

# csomagnévlista
for i in `ls -1 $gittdir`;do
    if [ ! "$i" == "Build-order" ];then
        for csomag in `ls -1 $gittdir/$i/packages`;do
            echo $csomag >>tmpfile
        done
    fi
done
cat tmpfile | sort -u >csomaglista
rm tmpfile

for ub in `ls -1 $gittdir`;do
    if [ ! "$ub" == "Build-order" ];then
        if [ -f $gittdir/$ub/build-depends ];then
            for bdep in `cat $gittdir/$ub/build-depends`;do
                if [ ! "$(grep ^$bdep$ csomaglista)" ];then
                    pirosecho "$ub fordításhoz kellene $bdep !"
                fi
            done
        fi
    fi
done
