#!/bin/bash

# A paraméterkéntként megadott csomagból építkező csomagtalálatok
# amiknek a build-depends fájljában a paraméter szerepel
#!! a bdeprak szkript lefuttatása után használható csak !!

function hiba () {
    echo "Használat: bdep <csomag>"
    exit 1
}

# csak a fordítási mappában megy és színes és ub tároló frissül
. ubfriss

if [ ! "$1" ];then
    pirosecho "Nincs megadva egy csomag sem!"
    hiba
fi

analdir=(`pwd`/devanal)
bdep=$analdir/bdep
rdep=$analdir/rdep

if [ ! -d $analdir ];then
    pirosecho "csak a bdeprak szkript futtatása után lehet használn!"
    exit 1
fi

lista=$(grep ^$1$ $bdep/* | sed s/:.*//g | sed s%.*\/%%g)
for elem in $lista;do
cd $gittdir/$elem >/dev/null
u2dinfo
cd -  >/dev/null
done
