#!/bin/bash

# A paraméterkéntként megadott csomagból építkező csomagtalálatok
# amiknek a build-depends fájljában a paraméter szerepel
#!! a bdeprak szkript lefuttatása után használható csak !!

function hiba () {
    echo "Használat: bdep <csomag>"
    exit 1
}

# csak a fordítási mappában megy és színes
. disztbe

gittdir=~/gittek/ubk/ub-$kisdiszt

if [ ! -d $gittdir ];then
    hiba "Nincs $gittdir !"
fi

if [ ! "$1" ];then
    pirosecho "Nincs megadva egy csomag sem!"
    hiba
fi

analdir=(`pwd`/devanal)
bdep=$analdir/bdep
rdep=$analdir/rdep

if [ ! -d $analdir ];then
    pirosecho "csak a bdeprak szkript futtatása után lehet használn!"
    hiba
fi

grep ^$1$ $bdep/* | sed s/:.*//g | sed s%.*\/%%g
