#!/bin/bash

# A paraméterkéntként megadott csomagból építkező csomagtalálatok
# amiknek a build-depends fájljában a paraméter szerepel
#!! a bdeprak szkript lefuttatása után használható csak !!

function hiba () {
    echo $1
    echo "Használat: bdep <csomag>"
    exit 1
}

diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|UBK1$\|2$\|3$\|4$' | sed s/.*-//)

if [ ! $diszt ];then
    hiba "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
fi

kisdiszt=$(echo $diszt | tr [:upper:] [:lower:])

gittem=~/gittek/ubk/ub-$kisdiszt

if [ ! -d $gittdir ];then
    hiba "Nincs $gittdir !"
fi

if [ ! "$1" ];then
    hiba "Nincs megadva egy csomag sem!"
fi

analdir=(`pwd`/devanal)
bdep=$analdir/bdep
rdep=$analdir/rdep

if [ ! -d $analdir ];then
    hiba "csak a bdeprak szkript futtatása után lehet használn!"
fi

grep ^$1$ $bdep/* | sed s/:.*//g | sed s%.*\/%%g
