#!/bin/bash
# A listafájl paraméterben felsorolt ubéket elhelyezi a $listafajl-ub mappába

function hiba () {
    echo "Használat: catbegyujt <listafájl> [32]"
	exit 1
}

# csak a fordítási mappában megy és színes és ub tároló frissül
. ubfriss

if [ -z "$1" ]; then
    pirosecho listafájl paraméter kell;
    hiba
fi

if [ ! -f "$1" ];then
    pirosecho "A $1 fájl nem létezik!"
    hiba
fi

listafajl=$1

ubmappa=$listafajl-ub

rm -rf $ubmappa
mkdir -p $ubmappa

for i in `cat $listafajl | sed s/#.*//g`;do
    cp -r $gittdir/$i $ubmappa/$i
done
