#!/bin/bash -e


function hiba () {
    echo $1
	echo 'Használat: csfelesleg <i386|amd64>'
	exit 1
}


diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|UBK1$\|2$\|3$\|4$|5$' | sed s/.*-//)

if [ ! $diszt ];then
    hiba "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
fi

kisdiszt=$(echo $diszt | tr [:upper:] [:lower:])
workdir=`pwd`
gittdir=~/gittek/ubk/ub-$kisdiszt

if [ ! -d $gittdir ];then
    hiba "Nincs klónozott $gittdir !"
fi

if [[ "$kisdiszt" > ubk2 ]];then
    arch=amd64
else
    if [ ! "$(echo $1 | grep '^i386$\|^amd64$')" ]; then
        hiba "Nem jó a $1 architektúra paraméter"
    else
       arch=$1
    fi
fi
# takarítások
rm -f tmpfile packagelist feleslegek

echo "A $gittdir frissítése"

cd $gittdir >/dev/null
git pull
cd - >/dev/null

echo "A $gittdir ubéinek packages neveinek összegyűjtése"

for ube in `ls -1 $gittdir`;do
    if [ ! "$ube" == "Build-order" ];then
        if [ -d $gittdir/$ube/packages ];then
            for packagename in `ls -1 $gittdir/$ube/packages`;do
                echo $packagename >>packagelist
            done
        else
            echo "Nincs $gittdir/$ube/packages mappa"
        fi
    fi
done

curlcim=http://download.ubk.hu/pkg/${diszt}/main/${arch}/

timeout 10 lynx -connect_timeout=5 -read_timeout=5 -passive-ftp -listonly -dump $curlcim  | sed -r 's/^.*\/([^\/]+)\/?$/\1/' | grep -E "uhu"$ > tmpfile

for csomag in `cat tmpfile`;do
#    filenev=$(grep ^"${i}"_ tmpfile)
package=$(echo $csomag  | sed s/_.*//)
if [ ! "$(grep ^$package$ packagelist)" ];then
    echo $csomag >>feleslegek  
    echo $csomag
fi
done
# takarítás
rm -f tmpfile packagelist
