#!/bin/bash -e

# Extrarelease fájlok összegyűjtő szkriptje csomaghalmaz újrafordításához.

# Az első paraméterben megadott architektúrának megfelelő ftp lelőhelyről összegyűjti a 
# megadott csomagnevek aktuális extrarelease értékeit egy újonnan a munkakönyvtárban létrehozott mappába.
# Az ide létrehozott fájlokat a /usr/src/UHUBUILD/ megfelelő mappájába másolva a build
# rendszer már azokkal fog dolgozni és a létrejövő csomag extrarelease értéke nagyobb lesz az ftp-n találhatónál.

function hiba () {
	echo 'Használat: curlextrarel <i386|amd64> <csomagsorozat|frissített-csomagok-ubéit-tartalmazó-mappa> '
	echo 'UBK3 esetén az architektúra paraméter elhagyható.'
	exit 1
}

# Hiba miatti kilépéskor maradhatott fájl törlése
rm -f tmpfile

# csak a fordítási mappában megy és színes
. disztbe

# Ha $diszt UBK3, és $1 i386, akkor hiba
if [[ "$diszt" > "UBK2" ]];then
    if [ "$(echo $1 | grep '^i386$')" ]; then
        pirosecho "csak UBK1 és UBK2 esetén lehet i386 a paraméter!"
        hiba
    else
        arch=amd64
        if [ "$(echo $1 | grep '^amd64$')" ]; then
            cspar=$2
        else
            cspar=$1
        fi
        erelmappa=erel
    fi
else
    if [ ! "$(echo $1 | grep '^i386$\|^amd64$')" ]; then
        pirosecho "Nem jó a $1 architektúra paraméter"
        hiba
    else
        arch=$1
    fi
    if [ ! "$2" ];then
        pirosecho "Nincs megadva egy csomag sem, vagy azok ubéit tartalmazó mappa!"
        hiba
    else
        cspar=$2
    fi
    erelmappa=erel-${arch}
fi
csomaghalmaz=""
if [ ! -d $cspar ];then
# csak a csomaghalmaz kell a paraméterlistából
    for csomag in "$@" ; do
        if [ ! $csomag == $arch ]; then
            csomaghalmaz=$(echo -e "$csomaghalmaz"'\n'"$csomag")
        fi
    done
else
    for csomag in `ls -1 $cspar`;do
        if [ -d $cspar/$csomag ];then
            csomaghalmaz=$(echo -e "$csomaghalmaz"'\n'"$csomag")
        else
            pirosecho "A $cspar/$csomag nem mappa!"
            hiba
        fi
    done
fi
curlcim=http://download.ubk.hu/pkg/${diszt}/main/${arch}/

# takarítások
rm -rf $erelmappa
mkdir $erelmappa

zoldecho " Az újrafordításhoz kellő extrarelease fájlok az $erelmappa mappába kerülnek."
lynx -connect_timeout=5 -listonly -dump $curlcim | sed 's%.*/%%g' | grep "uhu"$ > tmpfile

for i in $csomaghalmaz;do
if [ "$(grep ^"${i}"_ tmpfile)" ];then
    filenev=$(grep ^"${i}"_ tmpfile)
    echo $filenev
    nev=$(echo $filenev | sed "s/_$arch.*//g")
    extrareleasenev=$(echo $nev | sed  s/\.[0-9]*$//)
    extrarelease=$(echo $nev| sed s/.*-//g | sed s/[0-9]*\\.//g)
    #echo "$filenev $extrareleasenev $extrarelease"
    echo -e $extrarelease'\n' > $erelmappa/$extrareleasenev
fi
done
# takarítás
rm -f tmpfile
