#!/bin/bash

# A helyi csomagkészletben az egyes csomagok függőségeinek létét vizsgálja a dpkg-deb segítségével.
# A észlelt hiányosságok a csujra és a fugghibak fájlokban lesznek felsorolva

function hiba () {
    echo $1
    echo "Használat: fell [<amd64|i386>] |<t>]"
    exit 1
}


diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|UBK1$\|2$\|3$\|4$\|5$' | sed s/.*-//)

if [ ! $diszt ];then
    hiba "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
fi

kisdiszt=$(echo $diszt | tr [:upper:] [:lower:])

if [[ "$diszt" < "UBK3" ]] && [[ ! $1 ]];then
    hiba "UBK1 és UBK2 esetén kötelező az architectúra paraméter"
else
    if [[ "$diszt" > "UBK2" ]];then
        arch=amd64
    else
        arch=$1
    fi
fi
rm -f csomaglista
tukor=/usr/src/UHUBUILD/pkg/$diszt/main/$arch
lassu=""
if [ "$1" == "t" ] || [ "$2" == "t" ];then
    if [ ! -d $tukor ];then
        echo "Nincs $tukor ! A vizgálat lassú lesz"
    fi
    lassu=1
    curlcim=http://download.ubk.hu/pkg/${diszt}/main/${arch}/
    lynx -connect_timeout=5 -listonly -dump $curlcim | sed 's%.*/%%g' | grep "uhu"$ > csomaglista
else
ls -1 $tukor | grep -E "uhu"$ > csomaglista
fi

if [ $lassu ];then
    tarolo=tavoli
else
    tarolo=helyi
fi
    cat csomaglista | sed 's/.://g' >tmpfile
    rm csomaglista
    mv tmpfile csomaglista
for pkg in `cat csomaglista`;do
    if [ $lassu ];then
        cd /tmp
        wget -q --show-progress $curlcim/$pkg
        alldeps=$(dpkg-deb -I $pkg | grep Depends: \
            | sed 's/Depends: //' | sed 's/,/\n/g' | sed 's/^ //g')
        rm $pkg
        cd - > /dev/null
    else
        alldeps=$(dpkg-deb -I $tukor/$pkg | grep Depends: \
        | sed 's/Depends: //' | sed 's/,/\n/g' | sed 's/^ //g')
    fi
    novers=$(echo "$alldeps" | sed /\(/d)
    noversions=""
    for i in $novers;do
        noversions=$(echo $noversions" "$(echo ${i}_))
    done
    alldepends=$(echo "$noversions" "$(echo "$alldeps"  | grep -E '\)' \
        | sed s/\)//g | sed s/\(//g | sed s/\>//g | sed s/=//g | sed 's/  /_/g' | sed 's/.://g')" | sed -E 's/ /\n/')
    for de in $alldepends;do
        van=$(grep ^$de csomaglista)
        if [ ! "$van" ];then
            echo "$de kellene a $pkg csomagnak !" >>hibak
            echo "$de kellene a $pkg csomagnak, de az nincs a $tarolo tárolóban!"
            echo "$pkg csomagnak $de lenne az igénye!" >>cshibak
        fi
    done
done
cat hibak | sort -u >fugghibak
cat cshibak | sort -u >csujra
rm -f hibak
rm -f cshibak
rm -f csomaglista
