#!/bin/bash -e

function hiba () {
    echo "Használat: fordit <ub> [32]"
    echo "32 bites fordításhoz kell 3. paraméterként a 32 megadása"
	exit 1
}

# csak a fordítási mappában megy és színes
. disztbe

if [ -z "$1" ];then
    hiba "Nincs megadva ub!"
fi
ub=$1
if [ "$2" == "32" ];then
    arch="32"
    if [[ "$diszt" > "UBK2" ]];then
        pirosecho "32 bites fordítás csak UBK1/UBK2 esetén végezhető!"
        hiba
    fi
else
    arch="64"
fi

if [ ! -d $ub ];then
    pirosecho "Nincs $ub ub"
    hiba
fi
if [ -f /usr/bin/build-$diszt ];then
    disztem=$diszt
else
    disztem=$kisdiszt
fi
zoldecho "A $ub ub $arch bites fordítása..."

build-$disztem -ns -$arch $ub

rm -rf /usr/src/UHUBUILD/packages-$diszt/ub/$ub
