#!/bin/bash -e

function hiba () {
    echo "Használat: fordit <ub> [32] [la]"
    echo "32 bites fordításhoz kell 3. paraméterként a 32 megadása"
	exit 1
}

function keepla {
    steps="1 2 3"
    for step in $steps ;do
    cleanupfile="/var/uhubuild/$diszt/amd64/chroot$step/usr/lib/uhubuild/steps/cleanup"
        if [ -f $cleanupfile ];then
            sed 's%# .la%exit 0%' -i $cleanupfile
        fi
    done
}
function della {
    steps="1 2 3"
    for step in $steps ;do
    cleanupfile="/var/uhubuild/$diszt/amd64/chroot$step/usr/lib/uhubuild/steps/cleanup"
        if [ -f $cleanupfile ];then
            sed 's%exit 0%# .la%' -i $cleanupfile
        fi
    done
}

# csak a fordítási mappában megy és színes
. disztbe

if [ -z "$1" ];then
    hiba "Nincs megadva ub!"
fi
ub=$1
arch="64"
if [ "$2" == "32" ];then
    arch="32"
    if [[ "$diszt" > "UBK2" ]];then
        pirosecho "32 bites fordítás csak UBK1/UBK2 esetén végezhető!"
        hiba
    fi
fi
if [ "$2" == "la" ]; then
    lakell="la"
fi

if [ ! -d $ub ];then
    pirosecho "Nincs $ub ub"
    hiba
fi
if [ -f /usr/bin/build-$diszt ];then
    disztem=$diszt
else
    disztem=$kisdiszt
fi
zoldecho "A $ub ub $arch bites fordítása..."
della
if [ "$lakell" == "la" ];then
keepla
fi
build-$disztem -ns -$arch $ub
della

rm -rf /usr/src/UHUBUILD/packages-$diszt/ub/$ub
