#!/bin/bash
# Összegyűjti a paraméterként megadott listafájlból a frissíthető csomagokat.

function hiba () {
    echo $1
	echo 'Használat: frissgyujt <listafájl>'
	exit 1
}

diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|UBK1$\|2$\|3$' | sed s/.*-//)

if [ ! "$1" ]; then
    hiba "listafájl paraméter kell!"
fi

if [ ! $diszt ];then
    hiba "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
fi

kisdiszt=$(echo $diszt | tr [:upper:] [:lower:])
workdir=`pwd`
gitdir=~/gittek/ubk/ub-$kisdiszt

if [ ! -d $gitdir ];then
    hiba "Nincs klónozott $gitdir !"
fi


listafile=$1
if [ ! -f $listafile ];then
    hiba "Nincs $listafile listafájl!"
fi

echo "A $gitdir frissítése"
cd $gitdir >/dev/null
git pull
cd - >/dev/null

frissmappa=friss-$listafile
rm -rf $frissmappa
mkdir -p $frissmappa
rm -f $listafile-uj $listafile-ujnevek

for i in `cat $workdir/$listafile`;do
    if [ -d $gitdir/$i ]; then
        echo $i
        cd $gitdir/$i
        over=$(cat version)
        ujver=$(uhubuild-u2d)
        if [ ! "$ujver" ];then
            ujver=$(uhubuild-u2d)
            if [ ! "$ujver" ];then
                ujver=$(uhubuild-u2d)
            fi
            if [ ! "$ujver" ];then
                ujver=$(uhubuild-u2d)
            fi
            if [ ! "$ujver" ];then
                ujver=$(uhubuild-u2d)
            fi
        fi
        if [ "$ujver" ];then
            if [ ! "$over" == "$ujver" ];then
                cp -a $gitdir/$i $workdir/$frissmappa
                echo "$i $over -> $ujver" >>$workdir/$frissmappa/listafile-uj
#               echo $i >>$workdir/$listafile-ujnevek
            fi
        else
            mkdir -p $workdir/$frissmappa/u2dhiba
            cp -a $gitdir/$i $workdir/$frissmappa/u2dhiba
        fi
        cd - > /dev/null
    fi
done
echo
if [ -f $workdir/$frissmappa/listafile-uj ];then
echo "A frissíthető csomagok a $workdir/$frissmappa/listafile-uj fájlban vannak felsorolva."
echo "A frissíthető ubék a $workdir/$frissmappa mappában vannak"
else
rm -rf $workdir/$frissmappa
echo "Nincs frissíthető csomag."
fi
