#!/bin/bash
#leteszteli terminálban a listafájlban felsorolt csomagok frissíthetőségét

function hiba () {
	echo 'Használat: frissteszt <listafájl>'
	exit 1
}

# csak a fordítási mappában megy és színes és ub tároló frissül
. ubfriss

if [ ! "$1" ]; then
	pirosecho "listafájl paranéter kell!"
	hiba
fi

listafile=$1

if [ ! -f $listafile ];then
    pirosecho "Nincs $listafile listafájl!"
    hiba
fi

workdir=`pwd`

for i in `cat $listafile`;do
    if [ -d $gittdir/$i ]; then
        cd $gittdir/$i >/dev/null
            u2dinfo
        cd - >/dev/null
    else
        pirosecho "Nincs $gittdir/$i mappa!"
        hiba
    fi
done
