#!/bin/bash
# Összegyűjti a paraméterként megadott listafájlból a frissíthető csomagokat.

# csak a fordítási mappában megy és színes és ub tároló frissül
. ubfriss

# hibakezelés
# kiírja a paramétert és a használati útmutatót, majd kilép.
function hiba () {
	echo 'Használat: frissgyujt < listafájl | mappa >'
	exit 1
}

function verbe () {
ujver=`uhubuild-u2d`
if [ "$ujver" ]; then
   return
else
   ujver=`uhubuild-u2d`
   if [ "$ujver" ]; then
        return
   else
        ujver=`uhubuild-u2d`
        if [ "$ujver" ]; then
            return
        else
            ujver=`uhubuild-u2d`
            if [ "$ujver" ]; then
                return
            else
                ujver=`uhubuild-u2d`
                if [ "$ujver" ]; then
                    return
                else
                    ujver=`uhubuild-u2d`
                fi
            fi
        fi
    fi
fi
}
# Színes kiíratás
function verziobeszed () {
u2dfile="Nincs u2d!"
over=$(cat version)
szin=pirosecho
ujver=""
if [ -f u2d ] ; then
    verbe
    szin=normalecho
    if [ "$(cat u2d | grep noupdate)" ];then
        miert=$(cat u2d | grep noupdate | sed s/noupdate//)
        szin=kekecho
    else
        if [ "$ujver" == "$over" ]; then
            szin=zoldecho
            u2dfile=$ujver
        else
            szin=pirosecho
            u2dfile=$ujver
        fi
    fi
    alfanum=$(echo $ujver | grep -E '^[a-z]')
    if [[ ! "$ujver" ]] || [[ $alfanum ]] ;then
        szin=pirosecho
        u2dfile="Az u2d hibás!"
    fi
fi
if [ "$szin" == "zoldecho" ];then
echo $nev
elif [ "$szin" == "kekecho" ];then
kekecho -n "$nev "
echo $miert
else
echo -n "$nev"" ""$over > "
$szin "$u2dfile"
fi
}
# Összegyűjti a paraméterként megkapott listafájlból a frissíthető csomagokat.
 
function frissgy() {
    listafile=$1
    rm -rf $frissmappa
    mkdir -p $frissmappa
    rm -f $listafile-uj $listafile-ujnevek
    for nev in `cat $listafile`;do
        if [ -d $gittdir/$nev ]; then
                cd $gittdir/$nev
                if [ ! -f $gittdir/$nev/u2d ];then
                    verziobeszed
                    mkdir -p $workdir/$frissmappa/u2dhiany
                    cp -a $gittdir/$nev $workdir/$frissmappa/u2dhiany
                else
                    verziobeszed
                    if [ "$szin" == "kekecho" ];then
                        mkdir -p $workdir/frissek/noupdate
                        cp -a $gittdir/$nev $workdir/frissek/noupdate
                    fi
                    if [[ ! "$ujver" ]] || [[ $alfanum ]]; then
                        mkdir -p $workdir/frissek/u2dhiba
                        cp -a $gittdir/$nev $workdir/frissek/u2dhiba
                    elif [ ! "$over" == "$ujver" ];then
                            cp -a $gittdir/$nev $workdir/$frissmappa
                            echo "$nev $over -> $ujver" >>$workdir/$frissmappa/listafile-uj
                    fi
                fi
                cd - > /dev/null
        else
            pirosecho "Nincs $gittdir/$nev mappa!"
        fi
    done
    echo
    zoldecho "A $frissmappa vizsgálata  kész."
    if [ ! -z "$(ls -A $workdir/$frissmappa)" ];then
        echo
        echo "A frissíthető ubék a $workdir/$frissmappa mappában vannak."
    else
        rm -rf $workdir/$frissmappa
        kekecho "Nincs frissíthető csomag, a $workdir/$frissmappa mappa törölve."
    fi
}

# a paraméter alapján a kívánt tevékenység elvégzése

# Paraméter kell!
if [ ! "$1" ]; then
    pirosecho "Nincs listafájl, vagy mappa paraméter!"
    hiba
fi

ujver=global

mappa=$1

workdir=`pwd`
if [ -f $1 ];then # Létező fájl a paraméter
    frissmappa=$(echo $1 | sed s%.*/%%g)-friss
    rm -rf $workdir/$frissmappa
    mkdir -p $workdir/$frissmappa
    zoldecho "A $1 fájlban felsorolt ubék vizsgálata..."
    echo
    frissgy $mappa
elif [ -d $mappa ];then # Létező mappa a paraméter
    zoldecho "A $mappa mappában lévő ub listafájlok kiértékelése..."
    rm -rf $workdir/frissek
    mkdir -p $workdir/frissek
    for textek in `ls -1 $mappa`;do
        if [ ! -f $mappa/$textek ];then # Nem fájl a mappa aktuális eleme
            hiba "Nincs $mappa/$textek fájl!"
        else
            echo
            zoldecho "A $textek fájlban felsorolt ubék vizsgálata..."
            echo
            frissmappa=frissek/$textek
            frissgy $mappa/$textek
        fi
    done
else
    pirosecho "létező listafájl, vagy listafájlokat tartalmazó mappa paraméter kell!"
    hiba
fi
