#!/bin/bash
#leteszteli terminálban a listafájlban felsorolt csomagok frissíthetőségét

function hiba () {
    echo $1
	echo 'Használat: frissteszt <listafájl>'
	exit 1
}

diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|UBK1$\|2$\|3$' | sed s/.*-//)
if [ ! $diszt ];then
    hiba "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
fi

if [ ! "$1" ]; then
	hiba "listafájl paranéter kell!"
fi

listafile=$1

if [ ! -f $listafile ];then
    hiba "Nincs $listafile listafájl!"
fi

kisdiszt=$(echo $diszt | tr [:upper:] [:lower:])
workdir=`pwd`
gitdir=~/gittek/ubk/ub-$kisdiszt

if [ ! -d $gitdir ];then
    hiba "Nincs klónozott $gitdir !"
fi

echo "A $gitdir frissítése"
cd $gitdir >/dev/null
git pull
cd - >/dev/null

for i in `cat $listafile`;do
    if [ -d $gitdir/$i ]; then
        cd $gitdir/$i >/dev/null
            u2dinfo
        cd - >/dev/null
    else
        hiba "Nincs $gitdir/$i mappa!"
    fi
done
