#!/bin/bash
#leteszteli terminálban a listafájlban felsorolt csomagok frissíthetőségét

function hiba () {
    echo $1
	echo 'Használat: frissteszt <listafájl>'
	exit 1
}

diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|UBK1$\|2$\|3$\|4$' | sed s/.*-//)
if [ ! $diszt ];then
    hiba "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
fi

if [ ! "$1" ]; then
	hiba "listafájl paranéter kell!"
fi

listafile=$1

if [ ! -f $listafile ];then
    hiba "Nincs $listafile listafájl!"
fi

kisdiszt=$(echo $diszt | tr [:upper:] [:lower:])
workdir=`pwd`
gittdir=~/gittek/ubk/ub-$kisdiszt

if [ ! -d $gittdir ];then
    hiba "Nincs klónozott $gittdir !"
fi

echo "A $gittdir frissítése"
cd $gittdir >/dev/null
git pull
cd - >/dev/null

for i in `cat $listafile`;do
    if [ -d $gittdir/$i ]; then
        cd $gittdir/$i >/dev/null
            u2dinfo
        cd - >/dev/null
    else
        hiba "Nincs $gittdir/$i mappa!"
    fi
done
