#!/bin/bash
# Összegyűjti a listamappa mappában frissítendő lévő ubék miatt újraforgatandó ubéket az ujrakell mappába.
#

function hiba () {
	echo 'Használat: fugggyujt <listamappa>'
	exit 1
}

# csak a fordítási mappában megy és színes és ub tároló frissül
. ubfriss

if [ ! "$1" ];then
    pirosecho "mappa paraméter kell!"
    hiba
fi

forrdir=$1

if [ ! -d $forrdir ];then
    pirosecho "Nincs $forrdir mappa"
    hiba
fi

mappatart=$(ls -1 $forrdir)
if [ -z "$mappatart" ];then
pirosecho "a $forrdir mappa üres"
fi

ujrakell=ujraforditani
rm -rf $ujrakell
mkdir -p $ujrakell


for i in `ls -1 $forrdir`;do
    for j in `ls -1 $forrdir/$i/packages/`;do
        csomi=$(grep ^$j$ $gittdir/*/build-depends | sed s/\\/build-depends.*//g | sed "s|$gittdir\/||g")
        if [ "$csomi" ];then
            for csom in $csomi;do
                if [ ! -d "$forrdir/$csom" ];then
                    cp -a $gittdir/$csom $ujrakell/
                fi
            done
        fi
    done
done
if [ -z "$(ls -A $ujrakell)" ]; then
    rm -rf $ujrakell
    echo "Nincs újrafordítandó ubé."
    exit 0
else
    echo "Az újrafordítandó ubék a $ujrakell mappában vannak"
    echo "Ennek tartalma:"
    ls -1 $ujrakell
fi
curlextrarel ujraforditani
