#!/bin/bash
# Összegyűjti a listamappa mappában frissítendő lévő ubék miatt újraforgatandó ubéket az ujrakell mappába.
#

function hiba () {
    echo $1
	echo 'Használat: fugggyujt <listamappa>'
	exit 1
}

diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|UBK1$\|2$\|3$\|4$\|5$' | sed s/.*-//)
kisdiszt=$(echo $diszt | tr [:upper:] [:lower:])
workdir=`pwd`
gittdir=~/gittek/ubk/ub-$kisdiszt
forrdir=$1

if [ ! $diszt ];then
    hiba "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
fi

if [ ! "$1" ];then
    hiba
fi

if [ ! -d $forrdir ];then
    hiba "Nincs $forrdir mappa"
fi

if [ ! -d $gittdir ];then
    hiba "Nincs klónozott $gittdir !"
fi

echo "A $gittdir frissítése"
cd $gittdir >/dev/null
git pull
cd - >/dev/null

ujrakell=ujraforditani
rm -rf $ujrakell
mkdir -p $ujrakell


for i in `ls -1 $forrdir`;do
    for j in `ls -1 $forrdir/$i/packages/`;do
        csomi=$(grep ^$j$ $gittdir/*/build-depends | sed s/\\/build-depends.*//g | sed "s|$gittdir\/||g")
        if [ "$csomi" ];then
            for csom in $csomi;do
                if [ ! -d "$forrdir/$csom" ];then
                    cp -a $gittdir/$csom $ujrakell/
                fi
            done
        fi
    done
done
if [ -z "$(ls -A $ujrakell)" ]; then
    rm -rf $ujrakell
    echo "Nincs újrafordítandó ubé."
    exit 0
else
    echo "Az újrafordítandó ubék a $ujrakell mappában vannak"
    echo "Ennek tartalma:"
    ls -1 $ujrakell
fi
