#!/bin/bash

# Egy paraméterként megadott csomag mibenvoltának lekérdezése

function hiba () {
	echo 'Használat: miez <ub> '
	exit 1
}

# csak a fordítási mappában megy és színes és ub tároló frissül
. ubfriss

if [ ! -d $gittdir/$1 ];then
    pirosecho "nincs $1 ubmappa"
    hiba
fi
leiras=$(cat $gittdir/$1/packages/$1/summary/hu)
szekcio=$(cat $gittdir/$1/packages/$1/section)
acquire=$(cat $gittdir/$1/acquire)
zoldecho "$1 -- $leiras"
kekecho "Szekció -- $szekcio"
echo $acquire
