#!/bin/bash

# A paraméterkéntként megadott csomagból építkező csomagtalálatok
# amiknek a depends fájljában a paraméter szerepel
#!! a bdeprak szkript lefuttatása után használható csak !!

function hiba () {
    echo "Használat: rdep <csomag>"
    exit 1
}

# csak a fordítási mappában megy és színes
. disztbe

if [ ! "$1" ];then
    pirosecho "Nincs megadva egy csomag sem!"
    hiba
fi

analdir=(`pwd`/devanal)
bdep=$analdir/bdep
rdep=$analdir/rdep

if [ ! -d $analdir ];then
    pirosecho "csak a bdeprak szkript futtatása után lehet használn!"
    hiba
fi

grep ^$1$ $rdep/* | sed s/:.*//g | sed s%.*\/%%g
