#!/bin/bash

piros="$(echo -ne '\e[01;31m')"
kek="$(echo -ne '\e[01;34m')"
zold="$(echo -ne '\e[00;32m')"
normal="$(echo -ne '\e[00;00m')"

colorecho ()
{
	if [ -t 1 ]; then
		echo -ne "$1"
	fi
	shift
	echo "$@"
	if [ -t 1 ]; then
		echo -ne "$normal"
	fi
}

pirosecho   () { colorecho "$piros"   "$@"; }
kekecho  () { colorecho "$kek"  "$@"; }
zoldecho () { colorecho "$zold" "$@"; }
normalecho () { colorecho "$normal" "$@"; }
