#!/bin/bash
# Az ubk tároló helyi tükrének szinkronizálása

function hiba () {
	echo 'Használat: tukorfriss [ <amd64 | i386>]'
	exit 1
}

# csak a fordítási mappában megy és színes
. disztbe

if [[ "$diszt" < "UBK3" ]] && [[ ! $1 ]];then
    pirosecho "UBK1 és UBK2 esetén kötelező az architectúra paraméter"
    hiba
else
    if [[ "$diszt" > "UBK2" ]];then
        arch=amd64
    else
        arch=$1
    fi
fi

tukor=/usr/src/UHUBUILD/pkg/$diszt/main/

if [ ! -d $tukor ];then
    pirosecho "Nincs $tukor/$arch mappa"
    exit 1
fi
zoldecho "A $tukor/$arch mappa szinkronizálása..."
echo
rsync -razv --delete rsync://rsync.ubk.hu/pkgs/$diszt/main/$arch $tukor
