#!/bin/bash
# Az ubk tároló helyi tükrének szinkronizálása

function hiba () {
    echo $1
	echo 'Használat: tukorfriss [ <amd64 | i386>]'
	exit 1
}

diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|1$\|2$\|3$\|4$' | sed s/.*-//)

if [ ! $diszt ];then
    hiba "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
fi

if [[ "$diszt" < "UBK3" ]] && [[ ! $1 ]];then
    hiba "UBK1 és UBK2 esetén kötelező az architectúra paraméter"
else
    if [[ "$diszt" > "UBK2" ]];then
        arch=amd64
    else
        arch=$1
    fi
fi
kisdiszt=$(echo $diszt | tr [:upper:] [:lower:])

tukor=/usr/src/UHUBUILD/pkg/$diszt/main/

if [ ! -d $tukor ];then
    hiba "Nincs $tukor/$arch mappa"
fi

rsync -razv --delete rsync://rsync.ubk.hu/pkgs/$diszt/main/$arch $tukor
