#!/bin/bash

# u2d információt adó szkript
# Használata során bele kell lépni terminállal abba az mappába, melyben
# az u2d, sourcename, version fájlok vannak.
# Zölddel írja ki a verzót, ha azonos a version fájl tartalmával a megkapott érték, pirossal, ha más.

piros="$(echo -ne '\e[01;31m')"
kek="$(echo -ne '\e[01;34m')"
zold="$(echo -ne '\e[00;32m')"
normal="$(echo -ne '\e[00;00m')"

colorecho ()
{
	if [ -t 1 ]; then
		echo -ne "$1"
	fi
	shift
	echo "$@"
	if [ -t 1 ]; then
		echo -ne "$normal"
	fi
}

pirosecho   () { colorecho "$piros"   "$@"; }
kekecho  () { colorecho "$kek"  "$@"; }
zoldecho () { colorecho "$zold" "$@"; }
normalecho () { colorecho "$normal" "$@"; }

nev=`cat sourcename`
csomagolt=`cat version`
szin=pirosecho
u2dfile="Nincs u2d!"
if [ -f u2d ] ; then
    u2dfile=`uhubuild-u2d`
    if [ ! "$u2dfile" ]; then
        u2dfile=`uhubuild-u2d`
    fi
    if [ ! "$u2dfile" ]; then
        u2dfile=`uhubuild-u2d`
    fi
    if [ "$(cat u2d | grep noupdate)" ];then
        szin=kekecho
        u2dfile=$csomagolt
    else
        if [ "$u2dfile" == "$csomagolt" ]; then
            # zöldd
            szin=zoldecho
        else
            # piros
            szin=pirosecho
        fi
    fi
fi
normalecho -n "$nev"" ""$csomagolt "
$szin "$u2dfile"
