#!/bin/bash
# Az ubék meglétét ellenőrzo szkript

function hiba () {
    echo "Használat: ubellr"
    echo $1
	exit 1
}
# csak a fordítási mappában megy és színes és ub tároló frissül
. ubfriss
        arch=amd64

bintukor=/usr/src/UHUBUILD/pkg/UBK4/main/amd64/
rm -f lista*
ls -1 $gittdir >>lista
sed /Build-order/d -i lista
for cs in `cat lista`;do
    for i in `ls -1 $gittdir/$cs/packages`;do
        echo $i >>lista2
    done
done

for i in `cat lista2`;do
echo $i\_ >>lista3
done
for j in `cat lista3`;do
echo $j\* >>lista4
done
for k in `cat lista4`;do
    if [ ! -f $bintukor/$k ];then
        echo nincs $k
    fi
done

