#!/bin/bash -e

tukor=/usr/src/UHUBUILD/pkg
if [ -d $tukor ];then
rsync -razv --delete rsync://rsync.ubk.hu/pkgs/ $tukor
else
echo nincs $tukor
exit
fi

for i in $(ls -1 ~/gittek/ubk/);do
echo $i
echo "~/gittek/ubk/$i"
cd ~/gittek/ubk/$i
git pull
cd - > /dev/null
done

#synaptic tároló:
#file/usr/src/UHUBUILD/pkg/UBK4/main/amd64/
#./
