#!/bin/bash

# Az elkészült csomagok ubéit elhelyezi a helyi github tükörbe, utána kiíratja a github státuszt.
# A státusz ellenőrzése után mehet a commit és a push.
# használható az ubk1, ubk2 és ubk3 github helyi tükreinél is.

# csak a fordítási mappában megy és színes és ub tároló frissül
. ubfriss

keszdir=`pwd`/keszek
if [ ! -d $keszdir ];then
    pirosecho "Nincs $keszdir mappa!"
    exit 1
fi

zoldecho "A kész ubék elhelyezése..."
cd $gittdir
for i in `ls -1 $keszdir`;do
    rm -rf $i
    cp -r $keszdir/$i ./
    rm -rf $i/sources
    git add $i
done

git status
cd - >/dev/null
