#!/bin/bash

# Az elkészült csomagok ubéit elhelyezi a helyi github tükörbe, utána kiíratja a github státuszt.
# A státusz ellenőrzése után mehet a commit és a push.
# használható az ubk1, ubk2 és ubk3 github helyi tükreinél is.

function hiba () {
    echo $1
	exit 1
}

workdir=`pwd`
diszt=$(pwd | grep '/usr/src/UHUBUILD/UB-UBK\|1$\|2$\|3$' | sed s/.*-//)

if [ ! $diszt ];then
    hiba "Csak az UHUBUILD/UB-* könyvtárba lépve futtatható a szkript!"
fi

kisdiszt=$(echo $diszt | tr [:upper:] [:lower:])

keszdir=$workdir/keszek
if [ ! -d $keszdir ];then
    hiba "Nincs $keszdir !"
fi

ubdir=~/gittek/ubk/ub-$kisdiszt
if [ ! -d $ubdir ];then
    hiba "Nincs klónozott $ubdir!"
fi

echo "A $ubdir aktualizálása..."
cd $ubdir
git pull

echo "A kész ubék elhelyezése..."
for i in `ls -1 $keszdir`;do
    rm -rf $i
    cp -r $keszdir/$i ./
    rm -rf $i/sources
    git add $i
done

git status
cd -
