#!/bin/bash

# Az elkészült csomagok ubéit elhelyezi a helyi github tükörbe, utána kiíratja a github státuszt.
# A státusz ellenőrzése után mehet a commit és a push.
# használható az ubk1, ubk2 és ubk3 github helyi tükreinél is.

# csak a fordítási mappában megy és színes
. disztbe

keszdir=`pwd`/keszek
if [ ! -d $keszdir ];then
    pirosecho "Nincs $keszdir mappa!"
    exit 1
fi

ubdir=~/gittek/ubk/ub-$kisdiszt
if [ ! -d $ubdir ];then
    pirosecho "Nincs klónozott $ubdir!"
    exit 1
fi

zoldecho "A $ubdir aktualizálása..."
cd $ubdir
git pull

zoldecho "A kész ubék elhelyezése..."
for i in `ls -1 $keszdir`;do
    rm -rf $i
    cp -r $keszdir/$i ./
    rm -rf $i/sources
    git add $i
done

git status
cd - >/dev/null
