#!/bin/bash
# A fordítási sorrendfájlok összefűzése

# csak a fordítási mappában megy és színes
. disztbe

gitmappa=~/gittek/ubk/ub-${kisdiszt}
osszubrend=osszubrend
rm -f $osszubrend

if [ ! -d $gitmappa ];then
    pirosecho "Nincs klónozott $gitmappa"
    exit 1
fi
zoldecho "A $gitmappa aktualizálása..."
cd $gitmappa
git pull
cd - >/dev/null

kekecho "Az összefűzött fordítási sorrendfájl a $osszubrend fájl"
for i in `ls -1 $gitmappa/Build-order/*.txt | sort -V`;do
    cat $i >>$osszubrend
done
