#!/bin/bash

# színeket használunk
. szinek

function hiba () {
    pirosecho "Nincs megadva csomagnév"
    exit 1
}

if [ -z "$1" ]; then
    hiba
fi
pkgname=$1
tempname=$(echo $pkgname | sed 's/-/ /g')
perlname=""
for i in $tempname ;do
    perlname=$perlname-${i^}
done
perlname=${perlname#?}
perlname2=$(echo $perlname | sed s/-/::/g)
mkdir -p $pkgname/packages/$pkgname/summary
mkdir -p $pkgname/sources

echo $pkgname > $pkgname/sourcename
echo Libraries > $pkgname/packages/$pkgname/section
echo "UHU Linux Baráti Kör" > $pkgname/vendor
echo 1 >$pkgname/release
echo 'LICENSE*' > $pkgname/doc
echo 'README*' >> $pkgname/doc
echo 'UHU-Linux UBK3' > $pkgname/distribution
echo 'Kiss Attila <attus@enterpriseforever.com>' > $pkgname/maintainer
echo 'u2dcpan '"$perlname2" >$pkgname/u2d
echo "https://metacpan.org/pod/${perlname2}/" > $pkgname/homepage
touch $pkgname/packages/$pkgname/depends
echo "&perl modul" > $pkgname/packages/$pkgname/summary/hu
touch $pkgname/distribution
touch $pkgname/version
echo '#!/usr/bin/env dl' > $pkgname/acquire
echo >> $pkgname/acquire
echo "$perlname"'-${UB_VERSION}.tar.gz '"$perlname"'-${UB_VERSION}/' >> $pkgname/acquire
echo '	https://cpan.metacpan.org/modules/by-module/'"${perlname%%-*}/" >> $pkgname/acquire
echo '#!/bin/sh -eux' > $pkgname/install
echo >> $pkgname/install
cp $pkgname/install $pkgname/compile
echo 'ub_compile' >> $pkgname/compile
echo 'ub_install' >> $pkgname/install
chmod +x $pkgname/acquire $pkgname/compile $pkgname/install
